/**
 * NatureKart — Database Seeder
 * Seeds 60 products into MongoDB Atlas
 * Run: node seed.js  (from backend/ folder)
 */
const mongoose = require('mongoose');
require('dotenv').config();

const MONGO_URI = process.env.MONGO_URI;

const productSchema = new mongoose.Schema({
  name:        String,
  price:       Number,
  category:    String,
  description: String,
  image:       String,
  icon:        String,
  tag:         String,
  rating:      { type: Number, default: 4.5 },
  reviews:     { type: Number, default: 0 },
  inStock:     { type: Boolean, default: true },
  aiReason:    String,
}, { timestamps: true });

const PRODUCTS = [
  { name: "Ashwagandha Powder",       price: 349, rating: 4.8, reviews: 240, tag: "Bestseller", category: "Ayurveda",       icon: "🌿", image: "/images/ashwagandha.png",  inStock: true,  description: "Pure KSM-66 Ashwagandha root extract for stress relief & energy.",         aiReason: "Clinically proven adaptogen reduces cortisol levels by 28% and boosts energy naturally." },
  { name: "Turmeric Gold Capsules",   price: 299, rating: 4.7, reviews: 180, tag: "New",        category: "Supplements",    icon: "🟡", image: "/images/turmeric.png",      inStock: true,  description: "High-curcumin turmeric with black pepper for maximum absorption.",        aiReason: "Curcumin is nature's strongest anti-inflammatory, 40x more bioavailable with piperine." },
  { name: "Moringa Leaf Extract",     price: 449, rating: 4.9, reviews: 310, tag: "Top Rated",  category: "Supplements",    icon: "🌱", image: "/images/moringa.png",        inStock: true,  description: "Superfood-grade moringa leaf powder packed with 92+ nutrients.",          aiReason: "Contains 7x more vitamin C than oranges and 4x more calcium than milk." },
  { name: "Neem Face Wash",           price: 199, rating: 4.5, reviews: 120, tag: null,         category: "Skincare",       icon: "💚", image: "/images/neem-facewash.png",  inStock: true,  description: "Anti-bacterial neem & tea tree face wash for clear, acne-free skin.",     aiReason: "Neem's azadirachtin kills acne bacteria 3x faster than benzoyl peroxide." },
  { name: "Triphala Churna",          price: 249, rating: 4.6, reviews: 95,  tag: null,         category: "Ayurveda",       icon: "🪴", image: "/images/triphala.png",       inStock: true,  description: "Ancient Ayurvedic blend of three fruits for digestive wellness.",          aiReason: "3000-year-old formula supports gut microbiome with prebiotics and antioxidants." },
  { name: "Rose Hip Face Oil",        price: 599, rating: 4.8, reviews: 205, tag: "Premium",    category: "Skincare",       icon: "🌸", image: "/images/rosehip.png",        inStock: true,  description: "Cold-pressed rosehip oil rich in vitamin C for anti-ageing glow.",       aiReason: "Rich in retinoids and vitamin C — reduces fine lines by up to 23% in 8 weeks." },
  { name: "Tulsi Green Tea",          price: 179, rating: 4.7, reviews: 160, tag: null,         category: "Herbal Tea",     icon: "🍵", image: "/images/tulsi-tea.png",      inStock: true,  description: "Immunity-boosting tulsi & green tea blend, naturally caffeine light.",    aiReason: "Tulsi + EGCG combination boosts immune response and reduces stress hormones." },
  { name: "Amla Hair Serum",          price: 329, rating: 4.6, reviews: 140, tag: "Sale",       category: "Hair Care",      icon: "💧", image: "/images/amla-serum.png",     inStock: false, description: "Amla & Bhringraj enriched serum for hair growth and scalp health.",      aiReason: "Amla's vitamin C strengthens hair follicles, reducing hair fall by up to 45%." },
  { name: "Brahmi Memory Capsules",   price: 389, rating: 4.7, reviews: 88,  tag: "New",        category: "Supplements",    icon: "🧠", image: "/images/ashwagandha.png",   inStock: true,  description: "Bacopa monnieri extract to enhance memory and cognitive clarity.",        aiReason: "Bacosides in Brahmi rebuild neural pathways, improving memory recall by 30%." },
  { name: "Shilajit Resin",           price: 799, rating: 4.9, reviews: 432, tag: "Bestseller", category: "Ayurveda",       icon: "⚫", image: "/images/triphala.png",       inStock: true,  description: "Himalayan shilajit with 85+ minerals for peak vitality.",               aiReason: "Fulvic acid in Shilajit increases mitochondrial energy production by 56%." },
  { name: "Aloe Vera Gel",            price: 149, rating: 4.5, reviews: 310, tag: null,         category: "Skincare",       icon: "🌵", image: "/images/moringa.png",        inStock: true,  description: "Pure 99% aloe vera gel — hydrating, cooling, and soothing.",            aiReason: "Contains 75 active compounds including vitamins A, C, E and minerals." },
  { name: "Chamomile Sleep Tea",      price: 219, rating: 4.6, reviews: 74,  tag: null,         category: "Herbal Tea",     icon: "🌼", image: "/images/tulsi-tea.png",      inStock: true,  description: "Calming chamomile blend for restful sleep and relaxation.",              aiReason: "Apigenin binds to GABA receptors — improves sleep quality by 40% naturally." },
  { name: "Argan Hair Oil",           price: 499, rating: 4.8, reviews: 192, tag: "Premium",    category: "Hair Care",      icon: "✨", image: "/images/rosehip.png",        inStock: false, description: "100% pure Moroccan argan oil for silky, frizz-free hair.",              aiReason: "Oleic and linoleic acids penetrate hair shaft for deep nourishment." },
  { name: "Digestive Enzymes Mix",    price: 279, rating: 4.4, reviews: 56,  tag: null,         category: "Supplements",    icon: "🫀", image: "/images/turmeric.png",      inStock: true,  description: "Plant-based enzyme blend for optimal gut health and digestion.",         aiReason: "Multi-enzyme complex breaks down proteins, fats and carbs for better absorption." },
  { name: "Ginger Lemon Detox Tea",   price: 199, rating: 4.7, reviews: 134, tag: "Sale",       category: "Herbal Tea",     icon: "🍋", image: "/images/tulsi-tea.png",      inStock: true,  description: "Zesty ginger & lemon detox tea to cleanse and refresh.",               aiReason: "Gingerols reduce inflammation while lemon's antioxidants flush toxins daily." },
  { name: "Vitamin C Face Serum",     price: 449, rating: 4.8, reviews: 267, tag: "Bestseller", category: "Skincare",       icon: "🍊", image: "/images/neem-facewash.png", inStock: true,  description: "Brightening vitamin C serum with hyaluronic acid for radiant skin.",    aiReason: "Stable ascorbic acid reduces melanin production and boosts collagen synthesis." },
  { name: "Ginkgo Biloba",            price: 289, rating: 4.5, reviews: 145, tag: null,         category: "Supplements",    icon: "🧠", image: "/images/ashwagandha.png",   inStock: true,  description: "Premium ginkgo biloba for better brain circulation and memory.",         aiReason: "Flavonoids improve cerebral blood flow — shown to reduce memory decline by 26%." },
  { name: "Coconut Oil",              price: 249, rating: 4.6, reviews: 198, tag: null,         category: "Skincare",       icon: "🥥", image: "/images/moringa.png",        inStock: true,  description: "Cold-pressed extra virgin coconut oil for skin and hair.",              aiReason: "Lauric acid has proven antimicrobial activity and deep moisturizing properties." },
  { name: "Asafoetida Powder",        price: 149, rating: 4.4, reviews: 67,  tag: null,         category: "Ayurveda",       icon: "🟤", image: "/images/triphala.png",       inStock: true,  description: "Pure hing powder for digestive aid and culinary uses.",                 aiReason: "Ferulic acid and farnesiferol reduce bloating and IBS symptoms significantly." },
  { name: "Vitamin E Capsule",        price: 199, rating: 4.5, reviews: 223, tag: null,         category: "Supplements",    icon: "💊", image: "/images/neem-facewash.png", inStock: true,  description: "Natural vitamin E capsules for skin health and immunity.",              aiReason: "Tocopherols neutralize free radicals — reduces oxidative stress by 35%." },
  { name: "Cinnamon Tea",             price: 179, rating: 4.6, reviews: 112, tag: null,         category: "Herbal Tea",     icon: "🍫", image: "/images/tulsi-tea.png",      inStock: true,  description: "Cinnamon sticks tea for blood sugar balance and warmth.",               aiReason: "Cinnamaldehyde mimics insulin — reduces post-meal blood sugar spike by 29%." },
  { name: "Manjistha Capsule",        price: 349, rating: 4.7, reviews: 156, tag: "New",        category: "Ayurveda",       icon: "🔴", image: "/images/rosehip.png",        inStock: true,  description: "Manjistha herb for blood purification and skin health.",                aiReason: "Purifies lymphatic system and reduces skin pigmentation naturally." },
  { name: "Neem Powder",              price: 179, rating: 4.5, reviews: 189, tag: null,         category: "Skincare",       icon: "🌿", image: "/images/neem-facewash.png",  inStock: true,  description: "Neem leaf powder for face packs and dental health.",                   aiReason: "Contains limonoids which inhibit bacterial growth and clear skin blemishes." },
  { name: "Green Coffee Extract",     price: 399, rating: 4.6, reviews: 201, tag: "Sale",       category: "Supplements",    icon: "☕", image: "/images/turmeric.png",      inStock: true,  description: "Green coffee bean extract for weight management.",                      aiReason: "Chlorogenic acid reduces glucose absorption and boosts metabolism by 11%." },
  { name: "Tulsi Kadha",              price: 249, rating: 4.7, reviews: 178, tag: null,         category: "Herbal Tea",     icon: "🍵", image: "/images/tulsi-tea.png",      inStock: true,  description: "Concentrated tulsi decoction for cold and cough relief.",              aiReason: "Eugenol in Tulsi is a natural COX-2 inhibitor — soothes throat inflammation." },
  { name: "Bhringraj Oil",            price: 299, rating: 4.6, reviews: 134, tag: null,         category: "Hair Care",      icon: "💆", image: "/images/amla-serum.png",     inStock: true,  description: "Bhringraj oil for hair growth and premature greying.",                  aiReason: "Ecliptine activates hair follicle stem cells, proven to reduce hair loss by 40%." },
  { name: "Amla Powder",              price: 189, rating: 4.8, reviews: 267, tag: "Bestseller", category: "Ayurveda",       icon: "🫐", image: "/images/ashwagandha.png",   inStock: true,  description: "Dried amla powder rich in vitamin C for immunity.",                    aiReason: "Highest natural vitamin C source — boosts immunity 20x better than synthetic C." },
  { name: "Kesar Spice",              price: 599, rating: 4.9, reviews: 312, tag: "Premium",    category: "Herbal Tea",     icon: "🌸", image: "/images/rosehip.png",        inStock: true,  description: "Premium Kashmiri saffron for skin glow and wellness.",                  aiReason: "Crocin and safranal improve mood, sleep and skin luminosity simultaneously." },
  { name: "Psyllium Husk",            price: 199, rating: 4.5, reviews: 145, tag: null,         category: "Supplements",    icon: "🌾", image: "/images/triphala.png",       inStock: true,  description: "Isabgol husk for natural constipation relief.",                        aiReason: "Soluble fiber forms a gel that cleans colon walls and improves bowel regularity." },
  { name: "Tea Tree Face Wash",       price: 229, rating: 4.6, reviews: 167, tag: null,         category: "Skincare",       icon: "🍃", image: "/images/neem-facewash.png",  inStock: true,  description: "Tea tree oil face wash for acne-prone skin.",                          aiReason: "Terpinen-4-ol kills P. acnes bacteria on contact with no antibiotic resistance." },
  { name: "Garcinia Cambogia",        price: 349, rating: 4.4, reviews: 98,  tag: null,         category: "Supplements",    icon: "🍈", image: "/images/turmeric.png",      inStock: true,  description: "Garcinia extract for weight management support.",                       aiReason: "HCA blocks fat-producing enzyme citrate lyase and suppresses appetite naturally." },
  { name: "Mulethi Powder",           price: 229, rating: 4.6, reviews: 123, tag: null,         category: "Ayurveda",       icon: "🟤", image: "/images/moringa.png",        inStock: true,  description: "Licorice root powder for voice and throat care.",                       aiReason: "Glycyrrhizin soothes vocal cords and has anti-viral properties." },
  { name: "Lavender Essential Oil",   price: 349, rating: 4.7, reviews: 189, tag: "Premium",    category: "Essential Oils", icon: "💜", image: "/images/rosehip.png",        inStock: true,  description: "Pure lavender oil for aromatherapy and sleep.",                        aiReason: "Linalool reduces anxious neural activity — proven to extend sleep by 36 min/night." },
  { name: "Tulsi Masala Tea",         price: 199, rating: 4.6, reviews: 145, tag: null,         category: "Herbal Tea",     icon: "🍵", image: "/images/tulsi-tea.png",      inStock: true,  description: "Spiced tulsi tea blend with ginger and cardamom.",                    aiReason: "Masala spice blend warms respiratory tract and supports healthy digestion." },
  { name: "Saw Palmetto",             price: 449, rating: 4.5, reviews: 78,  tag: null,         category: "Supplements",    icon: "🌴", image: "/images/triphala.png",       inStock: true,  description: "Saw palmetto for prostate health in men.",                             aiReason: "Beta-sitosterol reduces DHT levels, supporting prostate and hair health in men." },
  { name: "Cucumber Face Pack",       price: 249, rating: 4.6, reviews: 156, tag: null,         category: "Skincare",       icon: "🥒", image: "/images/neem-facewash.png", inStock: true,  description: "Cucumber extract cooling face pack for refreshed skin.",               aiReason: "Caffeic acid in cucumber reduces skin inflammation and under-eye puffiness." },
  { name: "Black Seed Oil",           price: 399, rating: 4.7, reviews: 234, tag: "Bestseller", category: "Ayurveda",       icon: "⚫", image: "/images/triphala.png",       inStock: true,  description: "Black seed oil (Kalonji) for immunity and respiratory health.",        aiReason: "Thymoquinone is a potent immunomodulator — studied in over 650 clinical trials." },
  { name: "Ginseng Extract",          price: 549, rating: 4.7, reviews: 167, tag: "Premium",    category: "Supplements",    icon: "🌿", image: "/images/ashwagandha.png",   inStock: true,  description: "Korean ginseng for energy and stamina.",                               aiReason: "Ginsenosides stimulate energy production in mitochondria without caffeine crash." },
  { name: "Rose Water",               price: 149, rating: 4.8, reviews: 289, tag: "Bestseller", category: "Skincare",       icon: "🌹", image: "/images/rosehip.png",        inStock: true,  description: "Pure rose water toner for face and eyes.",                             aiReason: "Balances skin pH to 5.5 — the ideal level for healthy skin barrier function." },
  { name: "Black Pepper Powder",      price: 129, rating: 4.5, reviews: 145, tag: null,         category: "Ayurveda",       icon: "⚫", image: "/images/triphala.png",       inStock: true,  description: "Kali mirch for metabolism and immunity.",                              aiReason: "Piperine boosts nutrient absorption by up to 2000% and speeds metabolism." },
  { name: "Ginger Capsules",          price: 249, rating: 4.6, reviews: 178, tag: null,         category: "Supplements",    icon: "🫚", image: "/images/turmeric.png",      inStock: true,  description: "Ginger extract capsules for nausea and digestion.",                    aiReason: "6-shogaol reduces nausea signals in the brain — more effective than antiemetics." },
  { name: "Clove Essential Oil",      price: 299, rating: 4.6, reviews: 134, tag: null,         category: "Essential Oils", icon: "🌸", image: "/images/moringa.png",        inStock: true,  description: "Clove oil for toothache and oral health.",                             aiReason: "Eugenol is nature's strongest topical anesthetic — numbs pain in under 5 minutes." },
  { name: "Basil Seeds",              price: 99,  rating: 4.5, reviews: 98,  tag: null,         category: "Supplements",    icon: "🌱", image: "/images/moringa.png",        inStock: true,  description: "Sabja seeds for cooling drinks and digestion.",                        aiReason: "Swells 30x in water — creates fiber gel that cools body and aids gut function." },
  { name: "Multivitamin Complex",     price: 399, rating: 4.7, reviews: 234, tag: "Bestseller", category: "Supplements",    icon: "💊", image: "/images/neem-facewash.png", inStock: true,  description: "Complete multivitamin for daily health.",                              aiReason: "26 vitamins and minerals in one tablet — covers 100% daily recommended intake." },
  { name: "Beetroot Powder",          price: 299, rating: 4.6, reviews: 145, tag: "New",        category: "Supplements",    icon: "🫛", image: "/images/turmeric.png",      inStock: true,  description: "Beetroot powder for blood and energy.",                               aiReason: "Nitrates convert to nitric oxide — improves oxygen delivery and endurance by 16%." },
  { name: "Orange Peel Powder",       price: 199, rating: 4.5, reviews: 89,  tag: null,         category: "Skincare",       icon: "🍊", image: "/images/neem-facewash.png", inStock: true,  description: "Dried orange peel for face packs and Vitamin C.",                      aiReason: "Hesperidin and limonene in orange peel brighten skin and reduce dark spots." },
  { name: "Tulsi Classic Tea",        price: 159, rating: 4.7, reviews: 189, tag: null,         category: "Herbal Tea",     icon: "🍵", image: "/images/tulsi-tea.png",      inStock: true,  description: "Classic tulsi green tea for daily wellness.",                          aiReason: "Ursolic acid in Tulsi has proven adaptogenic and hepatoprotective properties." },
  { name: "Amla Candy",              price: 149, rating: 4.6, reviews: 267, tag: "Bestseller", category: "Ayurveda",       icon: "🍬", image: "/images/amla-serum.png",     inStock: true,  description: "Sugar-free amla candy for immunity on-the-go.",                       aiReason: "Portable vitamin C — provides 600mg natural ascorbic acid per piece." },
  { name: "Ashwagandha Roots",        price: 299, rating: 4.7, reviews: 145, tag: null,         category: "Ayurveda",       icon: "🌿", image: "/images/ashwagandha.png",   inStock: true,  description: "Whole ashwagandha root for custom formulations.",                      aiReason: "Withanolides in whole root offer maximum potency vs. extracts." },
  { name: "Turmeric Soap",            price: 99,  rating: 4.5, reviews: 178, tag: null,         category: "Skincare",       icon: "🧼", image: "/images/moringa.png",        inStock: true,  description: "Turmeric-infused soap for glowing skin.",                              aiReason: "Daily curcumin exposure on skin reduces melanin and blemishes in 4 weeks." },
  { name: "Moringa Capsules",         price: 399, rating: 4.8, reviews: 201, tag: "Top Rated",  category: "Supplements",    icon: "💊", image: "/images/turmeric.png",      inStock: true,  description: "Moringa in easy-to-take capsules.",                                    aiReason: "Complete amino acid profile makes Moringa a perfect plant protein source." },
  { name: "Neem Tablets",             price: 199, rating: 4.6, reviews: 156, tag: null,         category: "Ayurveda",       icon: "💊", image: "/images/moringa.png",        inStock: true,  description: "Neem tablets for blood purification.",                                 aiReason: "Nimbolide in neem inhibits inflammatory cytokines, purifying blood naturally." },
  { name: "Saffron Hair Oil",         price: 449, rating: 4.6, reviews: 98,  tag: null,         category: "Hair Care",      icon: "💆", image: "/images/amla-serum.png",     inStock: true,  description: "Saffron-infused hair oil for shine and growth.",                       aiReason: "Crocin in saffron improves scalp microcirculation, enhancing hair pigmentation." },
  { name: "Peppermint Tea",           price: 169, rating: 4.7, reviews: 167, tag: null,         category: "Herbal Tea",     icon: "🍃", image: "/images/tulsi-tea.png",      inStock: true,  description: "Refreshing peppermint for digestive health.",                          aiReason: "Menthol relaxes intestinal muscles, relieving IBS and bloating in 30 minutes." },
  { name: "Karela Juice",             price: 249, rating: 4.5, reviews: 89,  tag: null,         category: "Supplements",    icon: "🥬", image: "/images/turmeric.png",      inStock: true,  description: "Bitter gourd juice for blood sugar balance.",                          aiReason: "Charantin and polypeptide-P mimic insulin action — reduces fasting glucose." },
  { name: "Tulsi Drop",               price: 129, rating: 4.6, reviews: 145, tag: "New",        category: "Herbal Tea",     icon: "💧", image: "/images/tulsi-tea.png",      inStock: true,  description: "Concentrated tulsi drops for instant relief.",                        aiReason: "10x concentrated extract — one drop delivers full therapeutic tulsi dose." },
  { name: "Shikakai Powder",          price: 149, rating: 4.5, reviews: 123, tag: null,         category: "Hair Care",      icon: "🌿", image: "/images/neem-facewash.png", inStock: true,  description: "Shikakai for natural hair cleansing.",                                 aiReason: "Natural saponins cleanse scalp without stripping essential hair oils." },
  { name: "Reetha Powder",            price: 129, rating: 4.5, reviews: 98,  tag: null,         category: "Hair Care",      icon: "🫘", image: "/images/moringa.png",        inStock: true,  description: "Soap nuts for natural hair wash.",                                    aiReason: "Saponins gently remove oil and product buildup — safe for color-treated hair." },
  { name: "Giloy Capsules",           price: 299, rating: 4.7, reviews: 178, tag: "Bestseller", category: "Ayurveda",       icon: "🌿", image: "/images/ashwagandha.png",   inStock: true,  description: "Giloy (Tinospora) for immunity and fever.",                            aiReason: "Berberine in Giloy activates macrophages — boosts immune response by 60%." },
  { name: "Kesar Milk Powder",        price: 499, rating: 4.8, reviews: 223, tag: "Premium",    category: "Supplements",    icon: "🥛", image: "/images/tulsi-tea.png",      inStock: true,  description: "Saffron milk mix for skin glow and sleep.",                           aiReason: "Saffron + warm milk triggers serotonin release — natural sleep and mood booster." },
];

async function seed() {
  console.log('\n🌿 NatureKart — Database Seeder\n');

  try {
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB Atlas');

    const Product = mongoose.model('Product', productSchema);

    const existing = await Product.countDocuments();
    if (existing > 0) {
      console.log(`⚠️  Database already has ${existing} products.`);
      console.log('   Delete them in Atlas Compass first to re-seed.\n');
      await mongoose.disconnect();
      return;
    }

    await Product.insertMany(PRODUCTS);
    console.log(`✅ Seeded ${PRODUCTS.length} products into MongoDB Atlas!`);
    console.log('\n🚀 Your product store is ready. Open the Admin Panel to manage products.\n');
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
  } finally {
    await mongoose.disconnect();
    process.exit(0);
  }
}

seed();
